var places = ['Paris', 'London', 'New York', 'Tokyo', 'Dubai'];
console.log('====================================');
console.log('Original List', places);
console.log('====================================');
console.log('Sorted List', places.slice().sort());
console.log('====================================');
console.log('Original List', places);
console.log('====================================');
console.log('Reverse Alphabetical List', places.slice().sort().reverse());
console.log('====================================');
console.log('Original List', places);
console.log('====================================');
console.log('Reversed List', places.reverse());
console.log('====================================');
console.log('Reverse Back to Original List', places.reverse());
console.log('====================================');
console.log('Sorted List', places.sort());
console.log('====================================');
console.log('Reverse Sorted List', places.sort().reverse());
console.log('====================================');
